import { isValidElement } from 'react'
import clsx from 'clsx'

export { Pre as pre }

interface PreProps extends React.ComponentProps<'pre'> {}

function Pre(props: PreProps) {
  if (isValidElement(props.children) && props.children.props['data-theme']) {
    // generated by rehype-pretty-code
    return (
      <pre
        {...props}
        className={clsx(
          props.className,
          // rehype-pretty-code generates code blocks twice, so we can pick the color scheme
          props.children.props['data-theme'] === 'light'
            ? 'dark:hidden'
            : 'hidden dark:block',
        )}
      />
    )
  }

  return <pre {...props} />
}
