import { isValidElement } from 'react'
import clsx from 'clsx'

export { Div as div, Pre as pre }

interface DivProps extends React.ComponentProps<'div'> {
  'data-rehype-pretty-code-fragment'?: ''
}

function Div(props: DivProps) {
  // turn this div into an actual fragment by not rendering it
  if (typeof props['data-rehype-pretty-code-fragment'] !== 'undefined') {
    return props.children
  }
  return <div {...props} />
}

interface PreProps extends React.ComponentProps<'pre'> {}

function Pre(props: PreProps) {
  if (isValidElement(props.children) && props.children.props['data-theme']) {
    // generated by rehype-pretty-code
    return (
      <pre
        {...props}
        className={clsx(
          props.className,
          // rehype-pretty-code generates code blocks twice, so we can pick the color scheme
          props.children.props['data-theme'] === 'light'
            ? 'dark:hidden'
            : 'hidden dark:block',
        )}
      />
    )
  }

  return <pre {...props} />
}
