// flow-typed signature: aa3cb005412a9e0a451df07f1eeb1550
// flow-typed version: <<STUB>>/astroturf_v0.7.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'astroturf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

type Css = (string[], ...Interpolation[]) => {
  [string]: string,
}

type Interpolation =
  | string
  | number

type Styled = {
  (React$ElementType, options?: {
    allowAs: boolean,
  }): CreateStyledComponent,
  [tagName: string]: CreateStyledComponent,
}

type CreateStyledComponent =
  (string[], ...Interpolation[]) => typeof StyledComponent

class StyledComponent extends React$Component<{
  as: ?React$ElementType,
}> {
  static defaultProps = {
    as: undefined,
  }
}

declare module 'astroturf' {
  declare export type StyledComponent = StyledComponent
  declare export var css: Css
  declare export default Styled
}
