// flow-typed signature: 4a890bfc294ee218ea2dd2cddc79b7ac
// flow-typed version: <<STUB>>/cloudinary-core_v2.5.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloudinary-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloudinary-core' {
  declare export var Cloudinary: {
    new(config: {}): {
      url(id: string, options: {}): string,
    }
  }
}
