// flow-typed signature: 9f54211e170b0463793763cd52692709
// flow-typed version: <<STUB>>/emotion-theming_v9.2.6/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-theming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-theming' {
  declare export class ThemeProvider extends React$Component<{
    theme: *,
  }, *> {}
}
