// flow-typed signature: 74a82f7b9226db0c2de9fbe94500e785
// flow-typed version: <<STUB>>/webfontloader_v1.6.28/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webfontloader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webfontloader' {
  declare export default {
    load({
      google: {
        families: string[],
      },
    }): void,
  }
}
